// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// Defines values for OAuthTokenRequestGrantType.
const (
	ClientCredentials OAuthTokenRequestGrantType = "client_credentials"
	RefreshToken      OAuthTokenRequestGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the OAuthTokenRequestGrantType enum.
func (e OAuthTokenRequestGrantType) Valid() bool {
	switch e {
	case ClientCredentials:
		return true
	case RefreshToken:
		return true
	default:
		return false
	}
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	AccountId    string `json:"accountId"`
	Active       bool   `json:"active"`
	DisplayName  string `json:"displayName"`
	EmailAddress string `json:"emailAddress"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorMessages *[]string          `json:"errorMessages,omitempty"`
	Errors        *map[string]string `json:"errors,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// OAuthErrorResponse defines model for OAuthErrorResponse.
type OAuthErrorResponse struct {
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description"`
}

// OAuthTokenRequest defines model for OAuthTokenRequest.
type OAuthTokenRequest struct {
	ClientId     string                     `json:"client_id"`
	ClientSecret string                     `json:"client_secret"`
	GrantType    OAuthTokenRequestGrantType `json:"grant_type"`
	RefreshToken *string                    `json:"refresh_token,omitempty"`
}

// OAuthTokenRequestGrantType defines model for OAuthTokenRequest.GrantType.
type OAuthTokenRequestGrantType string

// OAuthTokenResponse defines model for OAuthTokenResponse.
type OAuthTokenResponse struct {
	AccessToken string  `json:"access_token"`
	ExpiresIn   int     `json:"expires_in"`
	Scope       *string `json:"scope,omitempty"`
	TokenType   string  `json:"token_type"`
}

// ExchangeOAuthTokenJSONRequestBody defines body for ExchangeOAuthToken for application/json ContentType.
type ExchangeOAuthTokenJSONRequestBody = OAuthTokenRequest
