// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// BitbucketBranchRestrictionRequest defines model for BitbucketBranchRestrictionRequest.
type BitbucketBranchRestrictionRequest struct {
	BranchMatchKind *string                   `json:"branch_match_kind,omitempty"`
	BranchType      *string                   `json:"branch_type,omitempty"`
	Groups          *[]map[string]interface{} `json:"groups,omitempty"`
	Kind            string                    `json:"kind"`
	Pattern         *string                   `json:"pattern,omitempty"`
	Users           *[]map[string]interface{} `json:"users,omitempty"`
	Value           *int                      `json:"value,omitempty"`
}

// BitbucketEnvironmentRequest defines model for BitbucketEnvironmentRequest.
type BitbucketEnvironmentRequest struct {
	EnvironmentType *struct {
		Name *string `json:"name,omitempty"`
		Type *string `json:"type,omitempty"`
	} `json:"environment_type,omitempty"`
	Name string `json:"name"`
	Rank *int   `json:"rank,omitempty"`
}

// CreateOrUpdateRepositoryJSONBody defines parameters for CreateOrUpdateRepository.
type CreateOrUpdateRepositoryJSONBody = map[string]interface{}

// UpdateBranchRestrictionJSONBody defines parameters for UpdateBranchRestriction.
type UpdateBranchRestrictionJSONBody = map[string]interface{}

// UpdateDeploymentEnvironmentJSONBody defines parameters for UpdateDeploymentEnvironment.
type UpdateDeploymentEnvironmentJSONBody = map[string]interface{}

// CreateOrUpdateGroupPermissionJSONBody defines parameters for CreateOrUpdateGroupPermission.
type CreateOrUpdateGroupPermissionJSONBody = map[string]interface{}

// CreateOrUpdateUserPermissionJSONBody defines parameters for CreateOrUpdateUserPermission.
type CreateOrUpdateUserPermissionJSONBody = map[string]interface{}

// CreateOrUpdatePipelineConfigJSONBody defines parameters for CreateOrUpdatePipelineConfig.
type CreateOrUpdatePipelineConfigJSONBody = map[string]interface{}

// CreateOrUpdateRepositoryJSONRequestBody defines body for CreateOrUpdateRepository for application/json ContentType.
type CreateOrUpdateRepositoryJSONRequestBody = CreateOrUpdateRepositoryJSONBody

// CreateBranchRestrictionJSONRequestBody defines body for CreateBranchRestriction for application/json ContentType.
type CreateBranchRestrictionJSONRequestBody = BitbucketBranchRestrictionRequest

// UpdateBranchRestrictionJSONRequestBody defines body for UpdateBranchRestriction for application/json ContentType.
type UpdateBranchRestrictionJSONRequestBody = UpdateBranchRestrictionJSONBody

// CreateDeploymentEnvironmentJSONRequestBody defines body for CreateDeploymentEnvironment for application/json ContentType.
type CreateDeploymentEnvironmentJSONRequestBody = BitbucketEnvironmentRequest

// UpdateDeploymentEnvironmentJSONRequestBody defines body for UpdateDeploymentEnvironment for application/json ContentType.
type UpdateDeploymentEnvironmentJSONRequestBody = UpdateDeploymentEnvironmentJSONBody

// CreateOrUpdateGroupPermissionJSONRequestBody defines body for CreateOrUpdateGroupPermission for application/json ContentType.
type CreateOrUpdateGroupPermissionJSONRequestBody = CreateOrUpdateGroupPermissionJSONBody

// CreateOrUpdateUserPermissionJSONRequestBody defines body for CreateOrUpdateUserPermission for application/json ContentType.
type CreateOrUpdateUserPermissionJSONRequestBody = CreateOrUpdateUserPermissionJSONBody

// CreateOrUpdatePipelineConfigJSONRequestBody defines body for CreateOrUpdatePipelineConfig for application/json ContentType.
type CreateOrUpdatePipelineConfigJSONRequestBody = CreateOrUpdatePipelineConfigJSONBody
