// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// ConfluenceNameRequired defines model for ConfluenceNameRequired.
type ConfluenceNameRequired struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreatePageRequest defines model for CreatePageRequest.
type CreatePageRequest struct {
	Body     *string `json:"body,omitempty"`
	ParentId *string `json:"parentId,omitempty"`
	SpaceId  string  `json:"spaceId"`
	Title    string  `json:"title"`
}

// CreatePermissionRequest defines model for CreatePermissionRequest.
type CreatePermissionRequest struct {
	Operation     *string `json:"operation,omitempty"`
	PrincipalId   *string `json:"principalId,omitempty"`
	PrincipalType string  `json:"principalType"`
}

// CreateRestrictionRequest defines model for CreateRestrictionRequest.
type CreateRestrictionRequest struct {
	Operation     string  `json:"operation"`
	PrincipalId   *string `json:"principalId,omitempty"`
	PrincipalType *string `json:"principalType,omitempty"`
}

// CreateSpaceRequest defines model for CreateSpaceRequest.
type CreateSpaceRequest struct {
	Description *string `json:"description,omitempty"`
	Key         string  `json:"key"`
	Name        string  `json:"name"`
	Type        *string `json:"type,omitempty"`
}

// UpdatePageJSONBody defines parameters for UpdatePage.
type UpdatePageJSONBody = map[string]interface{}

// UpdateSpaceJSONBody defines parameters for UpdateSpace.
type UpdateSpaceJSONBody = map[string]interface{}

// UpdateTemplateJSONBody defines parameters for UpdateTemplate.
type UpdateTemplateJSONBody = map[string]interface{}

// CreateContentRestrictionJSONRequestBody defines body for CreateContentRestriction for application/json ContentType.
type CreateContentRestrictionJSONRequestBody = CreateRestrictionRequest

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = CreatePageRequest

// UpdatePageJSONRequestBody defines body for UpdatePage for application/json ContentType.
type UpdatePageJSONRequestBody = UpdatePageJSONBody

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = CreateSpaceRequest

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = UpdateSpaceJSONBody

// CreateSpacePermissionJSONRequestBody defines body for CreateSpacePermission for application/json ContentType.
type CreateSpacePermissionJSONRequestBody = CreatePermissionRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = ConfluenceNameRequired

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateJSONBody
