// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// Defines values for CreateRoleAssignmentRequestPrincipalType.
const (
	Group CreateRoleAssignmentRequestPrincipalType = "group"
	User  CreateRoleAssignmentRequestPrincipalType = "user"
)

// Valid indicates whether the value is a known member of the CreateRoleAssignmentRequestPrincipalType enum.
func (e CreateRoleAssignmentRequestPrincipalType) Valid() bool {
	switch e {
	case Group:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for CreateRoleAssignmentRequestScope.
const (
	CreateRoleAssignmentRequestScopeOrg     CreateRoleAssignmentRequestScope = "org"
	CreateRoleAssignmentRequestScopeProduct CreateRoleAssignmentRequestScope = "product"
)

// Valid indicates whether the value is a known member of the CreateRoleAssignmentRequestScope enum.
func (e CreateRoleAssignmentRequestScope) Valid() bool {
	switch e {
	case CreateRoleAssignmentRequestScopeOrg:
		return true
	case CreateRoleAssignmentRequestScopeProduct:
		return true
	default:
		return false
	}
}

// Defines values for CreateRoleRequestScope.
const (
	CreateRoleRequestScopeOrg     CreateRoleRequestScope = "org"
	CreateRoleRequestScopeProduct CreateRoleRequestScope = "product"
)

// Valid indicates whether the value is a known member of the CreateRoleRequestScope enum.
func (e CreateRoleRequestScope) Valid() bool {
	switch e {
	case CreateRoleRequestScopeOrg:
		return true
	case CreateRoleRequestScopeProduct:
		return true
	default:
		return false
	}
}

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	AccountId string `json:"accountId"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Name string `json:"name"`
}

// CreateRoleAssignmentRequest defines model for CreateRoleAssignmentRequest.
type CreateRoleAssignmentRequest struct {
	PrincipalId   string                                   `json:"principalId"`
	PrincipalType CreateRoleAssignmentRequestPrincipalType `json:"principalType"`
	ProductId     *string                                  `json:"productId,omitempty"`
	RoleId        string                                   `json:"roleId"`
	Scope         CreateRoleAssignmentRequestScope         `json:"scope"`
}

// CreateRoleAssignmentRequestPrincipalType defines model for CreateRoleAssignmentRequest.PrincipalType.
type CreateRoleAssignmentRequestPrincipalType string

// CreateRoleAssignmentRequestScope defines model for CreateRoleAssignmentRequest.Scope.
type CreateRoleAssignmentRequestScope string

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
	Scope       *CreateRoleRequestScope `json:"scope,omitempty"`
}

// CreateRoleRequestScope defines model for CreateRoleRequest.Scope.
type CreateRoleRequestScope string

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	Label string `json:"label"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName  string `json:"displayName"`
	EmailAddress string `json:"emailAddress"`
}

// DeleteGroupParams defines parameters for DeleteGroup.
type DeleteGroupParams struct {
	GroupId string `form:"groupId" json:"groupId"`
}

// GetGroupParams defines parameters for GetGroup.
type GetGroupParams struct {
	GroupId string `form:"groupId" json:"groupId"`
}

// ListGroupMembersParams defines parameters for ListGroupMembers.
type ListGroupMembersParams struct {
	GroupId string `form:"groupId" json:"groupId"`
}

// RemoveGroupMemberParams defines parameters for RemoveGroupMember.
type RemoveGroupMemberParams struct {
	GroupId   string `form:"groupId" json:"groupId"`
	AccountId string `form:"accountId" json:"accountId"`
}

// AddGroupMemberParams defines parameters for AddGroupMember.
type AddGroupMemberParams struct {
	GroupId string `form:"groupId" json:"groupId"`
}

// UpdateRoleJSONBody defines parameters for UpdateRole.
type UpdateRoleJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	AccountId string `form:"accountId" json:"accountId"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Query string `form:"query" json:"query"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	DisplayName *string `json:"displayName,omitempty"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddMemberRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// CreateRoleAssignmentJSONRequestBody defines body for CreateRoleAssignment for application/json ContentType.
type CreateRoleAssignmentJSONRequestBody = CreateRoleAssignmentRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody UpdateRoleJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody
