// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// Defines values for CreateBoardRequestType.
const (
	Kanban CreateBoardRequestType = "kanban"
	Scrum  CreateBoardRequestType = "scrum"
)

// Valid indicates whether the value is a known member of the CreateBoardRequestType enum.
func (e CreateBoardRequestType) Valid() bool {
	switch e {
	case Kanban:
		return true
	case Scrum:
		return true
	default:
		return false
	}
}

// CreateAutomationRuleRequest defines model for CreateAutomationRuleRequest.
type CreateAutomationRuleRequest struct {
	Actions    *map[string]interface{} `json:"actions,omitempty"`
	Conditions *map[string]interface{} `json:"conditions,omitempty"`
	Name       string                  `json:"name"`
	State      *string                 `json:"state,omitempty"`
	Trigger    map[string]interface{}  `json:"trigger"`
}

// CreateBoardRequest defines model for CreateBoardRequest.
type CreateBoardRequest struct {
	Name string                 `json:"name"`
	Type CreateBoardRequestType `json:"type"`
}

// CreateBoardRequestType defines model for CreateBoardRequest.Type.
type CreateBoardRequestType string

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	Domain string `json:"domain"`
}

// CreateEmailRequest defines model for CreateEmailRequest.
type CreateEmailRequest struct {
	Active       *bool   `json:"active,omitempty"`
	DomainId     *string `json:"domainId,omitempty"`
	EmailAddress string  `json:"emailAddress"`
	SpaceId      *string `json:"spaceId,omitempty"`
}

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description    *string `json:"description,omitempty"`
	Key            string  `json:"key"`
	LeadAccountId  *string `json:"leadAccountId,omitempty"`
	Name           string  `json:"name"`
	ProjectTypeKey string  `json:"projectTypeKey"`
}

// NameRequired defines model for NameRequired.
type NameRequired struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UpdateBoardJSONBody defines parameters for UpdateBoard.
type UpdateBoardJSONBody = map[string]interface{}

// UpdateAutomationRuleJSONBody defines parameters for UpdateAutomationRule.
type UpdateAutomationRuleJSONBody = map[string]interface{}

// UpdateDashboardJSONBody defines parameters for UpdateDashboard.
type UpdateDashboardJSONBody = map[string]interface{}

// UpdateFieldJSONBody defines parameters for UpdateField.
type UpdateFieldJSONBody = map[string]interface{}

// UpdateFilterJSONBody defines parameters for UpdateFilter.
type UpdateFilterJSONBody = map[string]interface{}

// UpdateSecuritySchemeJSONBody defines parameters for UpdateSecurityScheme.
type UpdateSecuritySchemeJSONBody = map[string]interface{}

// UpdateIssueTypeJSONBody defines parameters for UpdateIssueType.
type UpdateIssueTypeJSONBody = map[string]interface{}

// UpdateIssueTypeSchemeJSONBody defines parameters for UpdateIssueTypeScheme.
type UpdateIssueTypeSchemeJSONBody = map[string]interface{}

// UpdateIncomingMailHandlerJSONBody defines parameters for UpdateIncomingMailHandler.
type UpdateIncomingMailHandlerJSONBody = map[string]interface{}

// UpdateOutgoingMailHandlerJSONBody defines parameters for UpdateOutgoingMailHandler.
type UpdateOutgoingMailHandlerJSONBody = map[string]interface{}

// UpdateNotificationSchemeJSONBody defines parameters for UpdateNotificationScheme.
type UpdateNotificationSchemeJSONBody = map[string]interface{}

// UpdatePermissionSchemeJSONBody defines parameters for UpdatePermissionScheme.
type UpdatePermissionSchemeJSONBody = map[string]interface{}

// UpdatePriorityJSONBody defines parameters for UpdatePriority.
type UpdatePriorityJSONBody = map[string]interface{}

// UpdatePrioritySchemeJSONBody defines parameters for UpdatePriorityScheme.
type UpdatePrioritySchemeJSONBody = map[string]interface{}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody = map[string]interface{}

// UpdateScreenJSONBody defines parameters for UpdateScreen.
type UpdateScreenJSONBody = map[string]interface{}

// UpdateScreenSchemeJSONBody defines parameters for UpdateScreenScheme.
type UpdateScreenSchemeJSONBody = map[string]interface{}

// CreateScreenTabFieldJSONBody defines parameters for CreateScreenTabField.
type CreateScreenTabFieldJSONBody struct {
	FieldId string `json:"fieldId"`
}

// UpdateWorkflowJSONBody defines parameters for UpdateWorkflow.
type UpdateWorkflowJSONBody = map[string]interface{}

// UpdateWorkflowSchemeJSONBody defines parameters for UpdateWorkflowScheme.
type UpdateWorkflowSchemeJSONBody = map[string]interface{}

// CreateBoardJSONRequestBody defines body for CreateBoard for application/json ContentType.
type CreateBoardJSONRequestBody = CreateBoardRequest

// UpdateBoardJSONRequestBody defines body for UpdateBoard for application/json ContentType.
type UpdateBoardJSONRequestBody = UpdateBoardJSONBody

// CreateAutomationRuleJSONRequestBody defines body for CreateAutomationRule for application/json ContentType.
type CreateAutomationRuleJSONRequestBody = CreateAutomationRuleRequest

// UpdateAutomationRuleJSONRequestBody defines body for UpdateAutomationRule for application/json ContentType.
type UpdateAutomationRuleJSONRequestBody = UpdateAutomationRuleJSONBody

// CreateDashboardJSONRequestBody defines body for CreateDashboard for application/json ContentType.
type CreateDashboardJSONRequestBody = NameRequired

// UpdateDashboardJSONRequestBody defines body for UpdateDashboard for application/json ContentType.
type UpdateDashboardJSONRequestBody = UpdateDashboardJSONBody

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomainRequest

// CreateEmailJSONRequestBody defines body for CreateEmail for application/json ContentType.
type CreateEmailJSONRequestBody = CreateEmailRequest

// CreateFieldJSONRequestBody defines body for CreateField for application/json ContentType.
type CreateFieldJSONRequestBody = CreateFieldRequest

// UpdateFieldJSONRequestBody defines body for UpdateField for application/json ContentType.
type UpdateFieldJSONRequestBody = UpdateFieldJSONBody

// CreateFilterJSONRequestBody defines body for CreateFilter for application/json ContentType.
type CreateFilterJSONRequestBody = NameRequired

// UpdateFilterJSONRequestBody defines body for UpdateFilter for application/json ContentType.
type UpdateFilterJSONRequestBody = UpdateFilterJSONBody

// CreateSecuritySchemeJSONRequestBody defines body for CreateSecurityScheme for application/json ContentType.
type CreateSecuritySchemeJSONRequestBody = NameRequired

// UpdateSecuritySchemeJSONRequestBody defines body for UpdateSecurityScheme for application/json ContentType.
type UpdateSecuritySchemeJSONRequestBody = UpdateSecuritySchemeJSONBody

// CreateIssueTypeJSONRequestBody defines body for CreateIssueType for application/json ContentType.
type CreateIssueTypeJSONRequestBody = NameRequired

// UpdateIssueTypeJSONRequestBody defines body for UpdateIssueType for application/json ContentType.
type UpdateIssueTypeJSONRequestBody = UpdateIssueTypeJSONBody

// CreateIssueTypeSchemeJSONRequestBody defines body for CreateIssueTypeScheme for application/json ContentType.
type CreateIssueTypeSchemeJSONRequestBody = NameRequired

// UpdateIssueTypeSchemeJSONRequestBody defines body for UpdateIssueTypeScheme for application/json ContentType.
type UpdateIssueTypeSchemeJSONRequestBody = UpdateIssueTypeSchemeJSONBody

// CreateIncomingMailHandlerJSONRequestBody defines body for CreateIncomingMailHandler for application/json ContentType.
type CreateIncomingMailHandlerJSONRequestBody = NameRequired

// UpdateIncomingMailHandlerJSONRequestBody defines body for UpdateIncomingMailHandler for application/json ContentType.
type UpdateIncomingMailHandlerJSONRequestBody = UpdateIncomingMailHandlerJSONBody

// CreateOutgoingMailHandlerJSONRequestBody defines body for CreateOutgoingMailHandler for application/json ContentType.
type CreateOutgoingMailHandlerJSONRequestBody = NameRequired

// UpdateOutgoingMailHandlerJSONRequestBody defines body for UpdateOutgoingMailHandler for application/json ContentType.
type UpdateOutgoingMailHandlerJSONRequestBody = UpdateOutgoingMailHandlerJSONBody

// CreateNotificationSchemeJSONRequestBody defines body for CreateNotificationScheme for application/json ContentType.
type CreateNotificationSchemeJSONRequestBody = NameRequired

// UpdateNotificationSchemeJSONRequestBody defines body for UpdateNotificationScheme for application/json ContentType.
type UpdateNotificationSchemeJSONRequestBody = UpdateNotificationSchemeJSONBody

// CreatePermissionSchemeJSONRequestBody defines body for CreatePermissionScheme for application/json ContentType.
type CreatePermissionSchemeJSONRequestBody = NameRequired

// UpdatePermissionSchemeJSONRequestBody defines body for UpdatePermissionScheme for application/json ContentType.
type UpdatePermissionSchemeJSONRequestBody = UpdatePermissionSchemeJSONBody

// CreatePriorityJSONRequestBody defines body for CreatePriority for application/json ContentType.
type CreatePriorityJSONRequestBody = NameRequired

// UpdatePriorityJSONRequestBody defines body for UpdatePriority for application/json ContentType.
type UpdatePriorityJSONRequestBody = UpdatePriorityJSONBody

// CreatePrioritySchemeJSONRequestBody defines body for CreatePriorityScheme for application/json ContentType.
type CreatePrioritySchemeJSONRequestBody = NameRequired

// UpdatePrioritySchemeJSONRequestBody defines body for UpdatePriorityScheme for application/json ContentType.
type UpdatePrioritySchemeJSONRequestBody = UpdatePrioritySchemeJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectJSONBody

// CreateScreenJSONRequestBody defines body for CreateScreen for application/json ContentType.
type CreateScreenJSONRequestBody = NameRequired

// UpdateScreenJSONRequestBody defines body for UpdateScreen for application/json ContentType.
type UpdateScreenJSONRequestBody = UpdateScreenJSONBody

// CreateScreenSchemeJSONRequestBody defines body for CreateScreenScheme for application/json ContentType.
type CreateScreenSchemeJSONRequestBody = NameRequired

// UpdateScreenSchemeJSONRequestBody defines body for UpdateScreenScheme for application/json ContentType.
type UpdateScreenSchemeJSONRequestBody = UpdateScreenSchemeJSONBody

// CreateScreenTabFieldJSONRequestBody defines body for CreateScreenTabField for application/json ContentType.
type CreateScreenTabFieldJSONRequestBody CreateScreenTabFieldJSONBody

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody = NameRequired

// UpdateWorkflowJSONRequestBody defines body for UpdateWorkflow for application/json ContentType.
type UpdateWorkflowJSONRequestBody = UpdateWorkflowJSONBody

// CreateWorkflowSchemeJSONRequestBody defines body for CreateWorkflowScheme for application/json ContentType.
type CreateWorkflowSchemeJSONRequestBody = NameRequired

// UpdateWorkflowSchemeJSONRequestBody defines body for UpdateWorkflowScheme for application/json ContentType.
type UpdateWorkflowSchemeJSONRequestBody = UpdateWorkflowSchemeJSONBody
