// Package specs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package specs

// StatuspageComponentGroupRequest defines model for StatuspageComponentGroupRequest.
type StatuspageComponentGroupRequest struct {
	ComponentGroup struct {
		Description *string `json:"description,omitempty"`
		Name        string  `json:"name"`
	} `json:"component_group"`
}

// StatuspageComponentRequest defines model for StatuspageComponentRequest.
type StatuspageComponentRequest struct {
	Component struct {
		Description *string `json:"description,omitempty"`
		GroupId     *string `json:"group_id,omitempty"`
		Name        string  `json:"name"`
		Status      *string `json:"status,omitempty"`
	} `json:"component"`
}

// StatuspageIncidentTemplateRequest defines model for StatuspageIncidentTemplateRequest.
type StatuspageIncidentTemplateRequest struct {
	Template struct {
		Body  *string `json:"body,omitempty"`
		Name  string  `json:"name"`
		Title *string `json:"title,omitempty"`
	} `json:"template"`
}

// StatuspageMaintenanceTemplateRequest defines model for StatuspageMaintenanceTemplateRequest.
type StatuspageMaintenanceTemplateRequest struct {
	Template struct {
		Body  *string `json:"body,omitempty"`
		Name  string  `json:"name"`
		Title *string `json:"title,omitempty"`
	} `json:"template"`
}

// StatuspagePageRequest defines model for StatuspagePageRequest.
type StatuspagePageRequest struct {
	Page struct {
		Name            string  `json:"name"`
		PageDescription *string `json:"page_description,omitempty"`
		Subdomain       *string `json:"subdomain,omitempty"`
	} `json:"page"`
}

// StatuspagePermissionRequest defines model for StatuspagePermissionRequest.
type StatuspagePermissionRequest struct {
	Permission struct {
		PrincipalId   string `json:"principal_id"`
		PrincipalType string `json:"principal_type"`
		Role          string `json:"role"`
	} `json:"permission"`
}

// StatuspageSubscriberRequest defines model for StatuspageSubscriberRequest.
type StatuspageSubscriberRequest struct {
	Subscriber struct {
		ComponentIds *[]string `json:"component_ids,omitempty"`
		Email        *string   `json:"email,omitempty"`
		Endpoint     *string   `json:"endpoint,omitempty"`
	} `json:"subscriber"`
}

// UpdateStatuspagePageJSONBody defines parameters for UpdateStatuspagePage.
type UpdateStatuspagePageJSONBody = map[string]interface{}

// UpdateStatuspageComponentGroupJSONBody defines parameters for UpdateStatuspageComponentGroup.
type UpdateStatuspageComponentGroupJSONBody = map[string]interface{}

// UpdateStatuspageComponentJSONBody defines parameters for UpdateStatuspageComponent.
type UpdateStatuspageComponentJSONBody = map[string]interface{}

// UpdateStatuspageIncidentTemplateJSONBody defines parameters for UpdateStatuspageIncidentTemplate.
type UpdateStatuspageIncidentTemplateJSONBody = map[string]interface{}

// UpdateStatuspageMaintenanceTemplateJSONBody defines parameters for UpdateStatuspageMaintenanceTemplate.
type UpdateStatuspageMaintenanceTemplateJSONBody = map[string]interface{}

// UpdateStatuspagePermissionJSONBody defines parameters for UpdateStatuspagePermission.
type UpdateStatuspagePermissionJSONBody = map[string]interface{}

// UpdateStatuspageSubscriberJSONBody defines parameters for UpdateStatuspageSubscriber.
type UpdateStatuspageSubscriberJSONBody = map[string]interface{}

// CreateStatuspagePageJSONRequestBody defines body for CreateStatuspagePage for application/json ContentType.
type CreateStatuspagePageJSONRequestBody = StatuspagePageRequest

// UpdateStatuspagePageJSONRequestBody defines body for UpdateStatuspagePage for application/json ContentType.
type UpdateStatuspagePageJSONRequestBody = UpdateStatuspagePageJSONBody

// CreateStatuspageComponentGroupJSONRequestBody defines body for CreateStatuspageComponentGroup for application/json ContentType.
type CreateStatuspageComponentGroupJSONRequestBody = StatuspageComponentGroupRequest

// UpdateStatuspageComponentGroupJSONRequestBody defines body for UpdateStatuspageComponentGroup for application/json ContentType.
type UpdateStatuspageComponentGroupJSONRequestBody = UpdateStatuspageComponentGroupJSONBody

// CreateStatuspageComponentJSONRequestBody defines body for CreateStatuspageComponent for application/json ContentType.
type CreateStatuspageComponentJSONRequestBody = StatuspageComponentRequest

// UpdateStatuspageComponentJSONRequestBody defines body for UpdateStatuspageComponent for application/json ContentType.
type UpdateStatuspageComponentJSONRequestBody = UpdateStatuspageComponentJSONBody

// CreateStatuspageIncidentTemplateJSONRequestBody defines body for CreateStatuspageIncidentTemplate for application/json ContentType.
type CreateStatuspageIncidentTemplateJSONRequestBody = StatuspageIncidentTemplateRequest

// UpdateStatuspageIncidentTemplateJSONRequestBody defines body for UpdateStatuspageIncidentTemplate for application/json ContentType.
type UpdateStatuspageIncidentTemplateJSONRequestBody = UpdateStatuspageIncidentTemplateJSONBody

// CreateStatuspageMaintenanceTemplateJSONRequestBody defines body for CreateStatuspageMaintenanceTemplate for application/json ContentType.
type CreateStatuspageMaintenanceTemplateJSONRequestBody = StatuspageMaintenanceTemplateRequest

// UpdateStatuspageMaintenanceTemplateJSONRequestBody defines body for UpdateStatuspageMaintenanceTemplate for application/json ContentType.
type UpdateStatuspageMaintenanceTemplateJSONRequestBody = UpdateStatuspageMaintenanceTemplateJSONBody

// CreateStatuspagePermissionJSONRequestBody defines body for CreateStatuspagePermission for application/json ContentType.
type CreateStatuspagePermissionJSONRequestBody = StatuspagePermissionRequest

// UpdateStatuspagePermissionJSONRequestBody defines body for UpdateStatuspagePermission for application/json ContentType.
type UpdateStatuspagePermissionJSONRequestBody = UpdateStatuspagePermissionJSONBody

// CreateStatuspageSubscriberJSONRequestBody defines body for CreateStatuspageSubscriber for application/json ContentType.
type CreateStatuspageSubscriberJSONRequestBody = StatuspageSubscriberRequest

// UpdateStatuspageSubscriberJSONRequestBody defines body for UpdateStatuspageSubscriber for application/json ContentType.
type UpdateStatuspageSubscriberJSONRequestBody = UpdateStatuspageSubscriberJSONBody
